### ISSUE TITLE
Better sorting of version numbers

### ISSUE THREAD

**Issue by beruic** [madskristensen/Packman#24]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: Newest

### Description
Version numbers are sorted wrongly.

### Steps to recreate
1. Change the extension to use CDNJS
2. Add the package `bootstrap-markdown`
3. Add the version property
4. Enter `2` so intellisense is activated

### Current behavior
Two things are wrong with the list that is shown:

1. The list is sorted alphabetically. This means that version `2.10.0` appears in the middle of the list, even though it is the highest version (see the below screenshot).
![packman_version_bug](https://cloud.githubusercontent.com/assets/724716/13432937/055ca0ca-dfd0-11e5-9397-1e6b611fbb81.png)
2. It is ordered lowest to highest. Usually you want the newest version, so the order should be highest to lowest.

### Expected behavior
I'd expect it to sort newest version to oldest. Versions are usually
The [.NET Version class](https://msdn.microsoft.com/en-us/library/system.version(v=vs.110).aspx) could be useful for sorting correctly, However I'm not shure how it parses beta numbers and such.

**Comment by madskristensen** [comment]
Unfortunately, property value Intellisense entries are sorted by the JSON editor regardless of how this extension sorts them. @mlorbetske do you know if this has been fixed?
